### ISSUE TITLE
Set up testing instance of Elasticsearch, populate with example data

### ISSUE THREAD

**Issue by brylie** [apinf/emq-analytics-dashboard#1]
> As a UX designer
I need to see the running software
so that I can continue my design process

> As a developer
I need some Elasticsearch dummy data
so I can focus on developing the dashboard design/layout

# Task
- [x] Set up Elasticsearch instance
- [x] Populate the Elasticsearch instance with some analytics data
- [x] Inform Apinf developers of the Internet address/port of the running Elasticsearch instance

cc: @bajiat

**Comment by frenchbread** [comment]
Elasticsearch `v5.2.0` is up and running.

**Comment by frenchbread** [comment]
Populated elasticsearch local & public instance with sample analytics data (using [this script](https://gist.github.com/frenchbread/d47e3b14f9fad9ff3db58bc0c2028e49))

**Comment by frenchbread** [comment]
This issue is completed. Should we close it?

**Comment by brylie** [comment]
Sure. How many records are there and how distinct are they? Also, please document how our team can use the EMQ instance, e.g. so we can publish MQTT messages.

**Comment by frenchbread** [comment]
There are 3085 items and they are generated randomly in given range. It looks like this:
<img width="1260" alt="screen shot 2017-02-16 at 15 47 37" src="https://cloud.githubusercontent.com/assets/2122679/23023703/6ff134ba-f45f-11e6-89ed-a545f908787e.png">

**Comment by brylie** [comment]
Great work! Lets deploy the Dashboard instance, so we can continue design work with @Nazarah.
